### PR TITLE
Add image registry option

### PR DESCRIPTION
**Pull request by GKotfis**
Add image registry option to allow pull images from other registries (i.e., deployed to cluster)

### CODE REVIEW

**Comment by groundhog2k** [comment]
Why not simply overwriting the repository value with `repository: my-registry.com/myrabbitmq` during your deployment?

**Comment by groundhog2k** [comment]
I thought about your suggestion again and will adapt it and add it to all the charts after a few tests.

**Comment by GKotfis** [comment]
@groundhog2k We used in project bitnami helm chart, but we have problems on Mac M1 with their rabbitmq image. That's why I started to look for other helm chart which use official rabbitmq images.

https://github.com/bitnami/charts/tree/master/bitnami/rabbitmq#rabbitmq-image-parameters

**Comment by groundhog2k** [comment]
I took your idea and rolled it out to all charts :-)  (https://github.com/groundhog2k/helm-charts/pull/1169/commits/2f4d393d4b3b323b26d87aa933ce48c4766e8049)

Thank you!

**Pull request closed without merging**
